### ISSUE TITLE
Warning: Illegal offset type in isset  ERROR

### ISSUE THREAD

**Issue by Xman078** [stommazh/lms#1]
Good Day

I tried installing the Plugin on wordpress 4.9.6. After installing the app I get the following errors:

( ! ) Warning: Illegal offset type in isset or empty in C:\wamp\www\lendempathy.co.za\wp-includes\capabilities.php on line 568
( ! ) Warning: Illegal offset type in isset or empty in C:\wamp\www\lendempathy.co.za\wp-includes\class-wp-user.php on line 752
( ! ) Warning: Illegal offset type in isset or empty in C:\wamp\www\lendempathy.co.za\wp-includes\capabilities.php on line 568
( ! ) Warning: Illegal offset type in isset or empty in C:\wamp\www\lendempathy.co.za\wp-includes\class-wp-user.php on line 752
( ! ) Warning: Illegal offset type in isset or empty in C:\wamp\www\lendempathy.co.za\wp-includes\capabilities.php on line 568
( ! ) Warning: Illegal offset type in isset or empty in C:\wamp\www\lendempathy.co.za\wp-includes\class-wp-user.php on line 752
( ! ) Warning: Cannot modify header information - headers already sent by (output started at C:\wamp\www\lendempathy.co.za\wp-includes\capabilities.php:568) in C:\wamp\www\lendempathy.co.za\wp-admin\includes\misc.php on line 1116

( ! ) Warning: Cannot modify header information - headers already sent by (output started at C:\wamp\www\lendempathy.co.za\wp-includes\capabilities.php:568) in C:\wamp\www\lendempathy.co.za\wp-includes\option.php on line 919

( ! ) Warning: Cannot modify header information - headers already sent by (output started at C:\wamp\www\lendempathy.co.za\wp-includes\capabilities.php:568) in C:\wamp\www\lendempathy.co.za\wp-includes\option.php on line 920
![screencapture-localhost-lendempathy-co-za-wp-admin-plugins-php-2018-06-18-12_15_21](https://user-images.githubusercontent.com/6306067/41530971-31f71a90-72f2-11e8-92ff-11f03183080c.png)

Please see screenshot attached.

Regards

**Comment by stommazh** [comment]
I'm sorry, but this project is now private and discontinued.
